package org.mobilitydb.meos;

/* AUTO-GENERATED by tools/codegen_facades.py — do not edit by hand.
 * Free functions from meos_transform.h
 * Methods emitted: 4 (stateless=4)
 * Source: the bundled JMEOS functions.GeneratedFunctions surface
 *         ∩ the streaming-relevance baseline.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsFreeTransform {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsFreeTransform() { /* utility */ }

    /**
     * MEOS {@code lwproj_lookup} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Classification: scalar in/out (default-stateless catch-all)</p>
     */
    public static int lwproj_lookup(int arg0, int arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "lwproj_lookup requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.lwproj_lookup(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code spheroid_init_from_srid} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Classification: scalar in/out (default-stateless catch-all)</p>
     */
    public static int spheroid_init_from_srid(int arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spheroid_init_from_srid requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spheroid_init_from_srid(arg0, arg1);
    }

    /**
     * MEOS {@code srid_check_latlong} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Classification: scalar in/out (default-stateless catch-all)</p>
     */
    public static void srid_check_latlong(int arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "srid_check_latlong requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        GeneratedFunctions.srid_check_latlong(arg0);
    }

    /**
     * MEOS {@code srid_is_latlong} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Classification: scalar in/out (default-stateless catch-all)</p>
     */
    public static int srid_is_latlong(int arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "srid_is_latlong requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.srid_is_latlong(arg0);
    }

}
