package org.mobilitydb.meos;

/* AUTO-GENERATED by tools/codegen_facades.py — do not edit by hand.
 * MEOS object-model class: Set
 * Methods emitted: 28 (bounded-state=17 · io-meta=4 · stateless=4 · windowed=3)
 * Source: the bundled JMEOS functions.GeneratedFunctions surface
 *         ∩ the streaming-relevance baseline.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsSet {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsSet() { /* utility */ }

    /**
     * MEOS {@code set_copy} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static Pointer set_copy(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_copy requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_copy(arg0);
    }

    /**
     * MEOS {@code set_to_span} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer set_to_span(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_to_span requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_to_span(arg0);
    }

    /**
     * MEOS {@code set_to_spanset} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer set_to_spanset(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_to_spanset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_to_spanset(arg0);
    }

    /**
     * MEOS {@code set_to_tbox} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer set_to_tbox(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_to_tbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_to_tbox(arg0);
    }

    /**
     * MEOS {@code set_basetype} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean set_basetype(int arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_basetype requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_basetype(arg0);
    }

    /**
     * MEOS {@code set_cmp} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int set_cmp(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_cmp requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_cmp(arg0, arg1);
    }

    /**
     * MEOS {@code set_eq} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean set_eq(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_eq requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_eq(arg0, arg1);
    }

    /**
     * MEOS {@code set_ge} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean set_ge(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_ge requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_ge(arg0, arg1);
    }

    /**
     * MEOS {@code set_gt} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean set_gt(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_gt requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_gt(arg0, arg1);
    }

    /**
     * MEOS {@code set_hash} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int set_hash(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_hash requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_hash(arg0);
    }

    /**
     * MEOS {@code set_hash_extended} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int set_hash_extended(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_hash_extended requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_hash_extended(arg0, arg1);
    }

    /**
     * MEOS {@code set_le} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean set_le(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_le requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_le(arg0, arg1);
    }

    /**
     * MEOS {@code set_lt} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean set_lt(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_lt requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_lt(arg0, arg1);
    }

    /**
     * MEOS {@code set_ne} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean set_ne(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_ne requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_ne(arg0, arg1);
    }

    /**
     * MEOS {@code set_num_values} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int set_num_values(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_num_values requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_num_values(arg0);
    }

    /**
     * MEOS {@code set_round} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer set_round(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_round requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_round(arg0, arg1);
    }

    /**
     * MEOS {@code set_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer set_spans(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_spans requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_spans(arg0);
    }

    /**
     * MEOS {@code set_spantype} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean set_spantype(int arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_spantype requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_spantype(arg0);
    }

    /**
     * MEOS {@code set_split_each_n_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer set_split_each_n_spans(Pointer arg0, int arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_split_each_n_spans requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_split_each_n_spans(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code set_split_n_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer set_split_n_spans(Pointer arg0, int arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_split_n_spans requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_split_n_spans(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code set_type} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean set_type(int arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_type requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_type(arg0);
    }

    /**
     * MEOS {@code set_extent_transfn} — tier <b>windowed</b>.
     * <p>Requires a window operator — caller wraps in an aggregate.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer set_extent_transfn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_extent_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_extent_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code set_union_finalfn} — tier <b>windowed</b>.
     * <p>Requires a window operator — caller wraps in an aggregate.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer set_union_finalfn(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_union_finalfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_union_finalfn(arg0);
    }

    /**
     * MEOS {@code set_union_transfn} — tier <b>windowed</b>.
     * <p>Requires a window operator — caller wraps in an aggregate.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer set_union_transfn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_union_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_union_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code set_as_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String set_as_hexwkb(Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_as_hexwkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_as_hexwkb(arg0, arg1);
    }

    /**
     * MEOS {@code set_as_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer set_as_wkb(Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_as_wkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_as_wkb(arg0, arg1);
    }

    /**
     * MEOS {@code set_from_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer set_from_hexwkb(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_from_hexwkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_from_hexwkb(arg0);
    }

    /**
     * MEOS {@code set_from_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer set_from_wkb(Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "set_from_wkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.set_from_wkb(arg0, arg1);
    }

}
