package org.mobilitydb.meos;

/* AUTO-GENERATED by tools/codegen_facades.py — do not edit by hand.
 * MEOS object-model class: TGeometry
 * Methods emitted: 6 (stateless=3 · io-meta=2 · bounded-state=1)
 * Source: the bundled JMEOS functions.GeneratedFunctions surface
 *         ∩ the streaming-relevance baseline.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTGeometry {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTGeometry() { /* utility */ }

    /**
     * MEOS {@code tgeometry_to_tcbuffer} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer tgeometry_to_tcbuffer(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeometry_to_tcbuffer requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeometry_to_tcbuffer(arg0);
    }

    /**
     * MEOS {@code tgeometry_to_tgeography} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer tgeometry_to_tgeography(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeometry_to_tgeography requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeometry_to_tgeography(arg0);
    }

    /**
     * MEOS {@code tgeometry_to_tgeompoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer tgeometry_to_tgeompoint(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeometry_to_tgeompoint requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeometry_to_tgeompoint(arg0);
    }

    /**
     * MEOS {@code tgeometry_type} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean tgeometry_type(int arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeometry_type requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeometry_type(arg0);
    }

    /**
     * MEOS {@code tgeometry_from_mfjson} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer tgeometry_from_mfjson(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeometry_from_mfjson requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeometry_from_mfjson(arg0);
    }

    /**
     * MEOS {@code tgeometry_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer tgeometry_in(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeometry_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeometry_in(arg0);
    }

}
