package org.mobilitydb.meos;

import functions.GeneratedFunctions;

/* AUTO-GENERATED by tools/codegen_facades.py — do not edit by hand.
 * Shared runtime helper: owns the single MEOS_AVAILABLE static-init across all
 * generated MeosOps* facades, so libmeos is probed exactly once per JVM. */
final class MeosOpsRuntime {

    static final boolean MEOS_AVAILABLE;

    static {
        boolean enabled = Boolean.parseBoolean(
                System.getProperty("mobilityflink.meos.enabled", "true"));
        boolean ok = false;
        if (enabled) {
            try {
                GeneratedFunctions.meos_initialize();
                ok = true;
            } catch (Throwable t) {
                ok = false;
            }
        }
        MEOS_AVAILABLE = ok;
    }

    private MeosOpsRuntime() { /* utility */ }
}
