package org.mobilitydb.meos;

/* AUTO-GENERATED by tools/codegen_facades.py — do not edit by hand.
 * MEOS object-model class: Temporal
 * Methods emitted: 99 (bounded-state=77 · cross-stream=7 · io-meta=5 · stateless=5 · windowed=5)
 * Source: the bundled JMEOS functions.GeneratedFunctions surface
 *         ∩ the streaming-relevance baseline.
 */

import functions.GeneratedFunctions;
import java.time.OffsetDateTime;
import jnr.ffi.Pointer;

public final class MeosOpsTemporal {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTemporal() { /* utility */ }

    /**
     * MEOS {@code temporal_copy} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static Pointer temporal_copy(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_copy requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_copy(arg0);
    }

    /**
     * MEOS {@code temporal_to_tinstant} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer temporal_to_tinstant(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_to_tinstant requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_to_tinstant(arg0);
    }

    /**
     * MEOS {@code temporal_to_tsequence} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer temporal_to_tsequence(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_to_tsequence requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_to_tsequence(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_to_tsequenceset} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer temporal_to_tsequenceset(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_to_tsequenceset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_to_tsequenceset(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_to_tstzspan} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer temporal_to_tstzspan(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_to_tstzspan requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_to_tstzspan(arg0);
    }

    /**
     * MEOS {@code temporal_after_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_after_timestamptz(Pointer arg0, OffsetDateTime arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_after_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_after_timestamptz(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_append_tinstant} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_append_tinstant(Pointer arg0, Pointer arg1, int arg2, double arg3, Pointer arg4, boolean arg5) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_append_tinstant requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_append_tinstant(arg0, arg1, arg2, arg3, arg4, arg5);
    }

    /**
     * MEOS {@code temporal_append_tsequence} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_append_tsequence(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_append_tsequence requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_append_tsequence(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_at_max} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_at_max(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_at_max requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_at_max(arg0);
    }

    /**
     * MEOS {@code temporal_at_min} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_at_min(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_at_min requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_at_min(arg0);
    }

    /**
     * MEOS {@code temporal_at_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_at_timestamptz(Pointer arg0, OffsetDateTime arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_at_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_at_timestamptz(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_at_tstzset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_at_tstzset(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_at_tstzset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_at_tstzset(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_at_tstzspan} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_at_tstzspan(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_at_tstzspan requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_at_tstzspan(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_at_tstzspanset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_at_tstzspanset(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_at_tstzspanset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_at_tstzspanset(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_at_values} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_at_values(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_at_values requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_at_values(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_basetype} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean temporal_basetype(int arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_basetype requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_basetype(arg0);
    }

    /**
     * MEOS {@code temporal_before_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_before_timestamptz(Pointer arg0, OffsetDateTime arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_before_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_before_timestamptz(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_delete_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_delete_timestamptz(Pointer arg0, OffsetDateTime arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_delete_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_delete_timestamptz(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_delete_tstzset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_delete_tstzset(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_delete_tstzset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_delete_tstzset(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_delete_tstzspan} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_delete_tstzspan(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_delete_tstzspan requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_delete_tstzspan(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_delete_tstzspanset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_delete_tstzspanset(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_delete_tstzspanset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_delete_tstzspanset(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_derivative} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_derivative(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_derivative requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_derivative(arg0);
    }

    /**
     * MEOS {@code temporal_duration} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_duration(Pointer arg0, boolean arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_duration requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_duration(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_dyntimewarp_distance} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double temporal_dyntimewarp_distance(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_dyntimewarp_distance requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_dyntimewarp_distance(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_dyntimewarp_path} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_dyntimewarp_path(Pointer arg0, Pointer arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_dyntimewarp_path requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_dyntimewarp_path(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_end_instant} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_end_instant(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_end_instant requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_end_instant(arg0);
    }

    /**
     * MEOS {@code temporal_end_sequence} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_end_sequence(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_end_sequence requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_end_sequence(arg0);
    }

    /**
     * MEOS {@code temporal_end_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static OffsetDateTime temporal_end_timestamptz(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_end_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_end_timestamptz(arg0);
    }

    /**
     * MEOS {@code temporal_frechet_distance} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double temporal_frechet_distance(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_frechet_distance requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_frechet_distance(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_frechet_path} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_frechet_path(Pointer arg0, Pointer arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_frechet_path requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_frechet_path(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_hash} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int temporal_hash(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_hash requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_hash(arg0);
    }

    /**
     * MEOS {@code temporal_hausdorff_distance} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double temporal_hausdorff_distance(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_hausdorff_distance requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_hausdorff_distance(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_insert} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_insert(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_insert requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_insert(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_instant_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_instant_n(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_instant_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_instant_n(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_instants} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_instants(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_instants requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_instants(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_interp} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static String temporal_interp(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_interp requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_interp(arg0);
    }

    /**
     * MEOS {@code temporal_lower_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean temporal_lower_inc(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_lower_inc requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_lower_inc(arg0);
    }

    /**
     * MEOS {@code temporal_max_instant} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_max_instant(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_max_instant requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_max_instant(arg0);
    }

    /**
     * MEOS {@code temporal_merge} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_merge(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_merge requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_merge(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_merge_array} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_merge_array(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_merge_array requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_merge_array(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_min_instant} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_min_instant(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_min_instant requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_min_instant(arg0);
    }

    /**
     * MEOS {@code temporal_minus_max} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_minus_max(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_minus_max requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_minus_max(arg0);
    }

    /**
     * MEOS {@code temporal_minus_min} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_minus_min(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_minus_min requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_minus_min(arg0);
    }

    /**
     * MEOS {@code temporal_minus_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_minus_timestamptz(Pointer arg0, OffsetDateTime arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_minus_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_minus_timestamptz(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_minus_tstzset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_minus_tstzset(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_minus_tstzset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_minus_tstzset(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_minus_tstzspan} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_minus_tstzspan(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_minus_tstzspan requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_minus_tstzspan(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_minus_tstzspanset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_minus_tstzspanset(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_minus_tstzspanset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_minus_tstzspanset(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_minus_values} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer temporal_minus_values(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_minus_values requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_minus_values(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_num_instants} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int temporal_num_instants(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_num_instants requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_num_instants(arg0);
    }

    /**
     * MEOS {@code temporal_num_sequences} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int temporal_num_sequences(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_num_sequences requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_num_sequences(arg0);
    }

    /**
     * MEOS {@code temporal_num_timestamps} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int temporal_num_timestamps(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_num_timestamps requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_num_timestamps(arg0);
    }

    /**
     * MEOS {@code temporal_round} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_round(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_round requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_round(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_scale_time} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_scale_time(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_scale_time requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_scale_time(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_segm_duration} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_segm_duration(Pointer arg0, Pointer arg1, boolean arg2, boolean arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_segm_duration requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_segm_duration(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code temporal_segments} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_segments(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_segments requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_segments(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_sequence_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_sequence_n(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_sequence_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_sequence_n(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_sequences} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_sequences(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_sequences requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_sequences(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_set_interp} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_set_interp(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_set_interp requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_set_interp(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_shift_scale_time} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_shift_scale_time(Pointer arg0, Pointer arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_shift_scale_time requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_shift_scale_time(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_shift_time} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_shift_time(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_shift_time requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_shift_time(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_simplify_dp} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_simplify_dp(Pointer arg0, double arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_simplify_dp requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_simplify_dp(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_simplify_max_dist} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_simplify_max_dist(Pointer arg0, double arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_simplify_max_dist requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_simplify_max_dist(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_simplify_min_dist} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_simplify_min_dist(Pointer arg0, double arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_simplify_min_dist requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_simplify_min_dist(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_simplify_min_tdelta} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_simplify_min_tdelta(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_simplify_min_tdelta requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_simplify_min_tdelta(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_spans(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_spans requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_spans(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_split_each_n_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_split_each_n_spans(Pointer arg0, int arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_split_each_n_spans requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_split_each_n_spans(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_split_n_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_split_n_spans(Pointer arg0, int arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_split_n_spans requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_split_n_spans(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_start_instant} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_start_instant(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_start_instant requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_start_instant(arg0);
    }

    /**
     * MEOS {@code temporal_start_sequence} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_start_sequence(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_start_sequence requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_start_sequence(arg0);
    }

    /**
     * MEOS {@code temporal_start_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static OffsetDateTime temporal_start_timestamptz(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_start_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_start_timestamptz(arg0);
    }

    /**
     * MEOS {@code temporal_stops} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_stops(Pointer arg0, double arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_stops requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_stops(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_subtype} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static String temporal_subtype(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_subtype requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_subtype(arg0);
    }

    /**
     * MEOS {@code temporal_time} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_time(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_time requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_time(arg0);
    }

    /**
     * MEOS {@code temporal_time_bins} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_time_bins(Pointer arg0, Pointer arg1, OffsetDateTime arg2, Pointer arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_time_bins requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_time_bins(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code temporal_time_split} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_time_split(Pointer arg0, Pointer arg1, OffsetDateTime arg2, Pointer arg3, Pointer arg4) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_time_split requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_time_split(arg0, arg1, arg2, arg3, arg4);
    }

    /**
     * MEOS {@code temporal_timestamps} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_timestamps(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_timestamps requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_timestamps(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_timestamptz_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_timestamptz_n(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_timestamptz_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_timestamptz_n(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_tprecision} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_tprecision(Pointer arg0, Pointer arg1, OffsetDateTime arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_tprecision requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_tprecision(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_tsample} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_tsample(Pointer arg0, Pointer arg1, OffsetDateTime arg2, int arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_tsample requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_tsample(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code temporal_type} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean temporal_type(int arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_type requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_type(arg0);
    }

    /**
     * MEOS {@code temporal_update} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer temporal_update(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_update requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_update(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code temporal_upper_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean temporal_upper_inc(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_upper_inc requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_upper_inc(arg0);
    }

    /**
     * MEOS {@code temporal_extent_transfn} — tier <b>windowed</b>.
     * <p>Requires a window operator — caller wraps in an aggregate.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer temporal_extent_transfn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_extent_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_extent_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_merge_combinefn} — tier <b>windowed</b>.
     * <p>Requires a window operator — caller wraps in an aggregate.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer temporal_merge_combinefn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_merge_combinefn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_merge_combinefn(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_merge_transfn} — tier <b>windowed</b>.
     * <p>Requires a window operator — caller wraps in an aggregate.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer temporal_merge_transfn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_merge_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_merge_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_tagg_finalfn} — tier <b>windowed</b>.
     * <p>Requires a window operator — caller wraps in an aggregate.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer temporal_tagg_finalfn(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_tagg_finalfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_tagg_finalfn(arg0);
    }

    /**
     * MEOS {@code temporal_tcount_transfn} — tier <b>windowed</b>.
     * <p>Requires a window operator — caller wraps in an aggregate.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer temporal_tcount_transfn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_tcount_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_tcount_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_cmp} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 2 temporals</p>
     */
    public static int temporal_cmp(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_cmp requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_cmp(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_eq} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 2 temporals</p>
     */
    public static boolean temporal_eq(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_eq requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_eq(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_ge} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 2 temporals</p>
     */
    public static boolean temporal_ge(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_ge requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_ge(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_gt} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 2 temporals</p>
     */
    public static boolean temporal_gt(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_gt requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_gt(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_le} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 2 temporals</p>
     */
    public static boolean temporal_le(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_le requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_le(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_lt} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 2 temporals</p>
     */
    public static boolean temporal_lt(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_lt requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_lt(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_ne} — tier <b>cross-stream</b>.
     * <p>Pairwise across streams — caller wraps in a join.</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 2 temporals</p>
     */
    public static boolean temporal_ne(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_ne requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_ne(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_as_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String temporal_as_hexwkb(Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_as_hexwkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_as_hexwkb(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_as_mfjson} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String temporal_as_mfjson(Pointer arg0, boolean arg1, int arg2, int arg3, String arg4) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_as_mfjson requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_as_mfjson(arg0, arg1, arg2, arg3, arg4);
    }

    /**
     * MEOS {@code temporal_as_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer temporal_as_wkb(Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_as_wkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_as_wkb(arg0, arg1);
    }

    /**
     * MEOS {@code temporal_from_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer temporal_from_hexwkb(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_from_hexwkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_from_hexwkb(arg0);
    }

    /**
     * MEOS {@code temporal_from_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer temporal_from_wkb(Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "temporal_from_wkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.temporal_from_wkb(arg0, arg1);
    }

}
