package org.mobilitydb.meos;

/* AUTO-GENERATED by tools/codegen_facades.py — do not edit by hand.
 * MEOS object-model class: DateSpan
 * Methods emitted: 9 (bounded-state=5 · io-meta=2 · stateless=2)
 * Source: the bundled JMEOS functions.GeneratedFunctions surface
 *         ∩ the streaming-relevance baseline.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsDateSpan {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsDateSpan() { /* utility */ }

    /**
     * MEOS {@code datespan_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static Pointer datespan_make(int arg0, int arg1, boolean arg2, boolean arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "datespan_make requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.datespan_make(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code datespan_to_tstzspan} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer datespan_to_tstzspan(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "datespan_to_tstzspan requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.datespan_to_tstzspan(arg0);
    }

    /**
     * MEOS {@code datespan_bins} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer datespan_bins(Pointer arg0, Pointer arg1, int arg2, Pointer arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "datespan_bins requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.datespan_bins(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code datespan_duration} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer datespan_duration(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "datespan_duration requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.datespan_duration(arg0);
    }

    /**
     * MEOS {@code datespan_lower} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int datespan_lower(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "datespan_lower requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.datespan_lower(arg0);
    }

    /**
     * MEOS {@code datespan_shift_scale} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer datespan_shift_scale(Pointer arg0, int arg1, int arg2, boolean arg3, boolean arg4) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "datespan_shift_scale requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.datespan_shift_scale(arg0, arg1, arg2, arg3, arg4);
    }

    /**
     * MEOS {@code datespan_upper} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int datespan_upper(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "datespan_upper requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.datespan_upper(arg0);
    }

    /**
     * MEOS {@code datespan_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer datespan_in(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "datespan_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.datespan_in(arg0);
    }

    /**
     * MEOS {@code datespan_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String datespan_out(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "datespan_out requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.datespan_out(arg0);
    }

}
