package org.mobilitydb.meos;

/* AUTO-GENERATED by tools/codegen_facades.py — do not edit by hand.
 * MEOS object-model class: DateSet
 * Methods emitted: 9 (bounded-state=5 · io-meta=2 · stateless=2)
 * Source: the bundled JMEOS functions.GeneratedFunctions surface
 *         ∩ the streaming-relevance baseline.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsDateSet {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsDateSet() { /* utility */ }

    /**
     * MEOS {@code dateset_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static Pointer dateset_make(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "dateset_make requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.dateset_make(arg0, arg1);
    }

    /**
     * MEOS {@code dateset_to_tstzset} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer dateset_to_tstzset(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "dateset_to_tstzset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.dateset_to_tstzset(arg0);
    }

    /**
     * MEOS {@code dateset_end_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int dateset_end_value(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "dateset_end_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.dateset_end_value(arg0);
    }

    /**
     * MEOS {@code dateset_shift_scale} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer dateset_shift_scale(Pointer arg0, int arg1, int arg2, boolean arg3, boolean arg4) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "dateset_shift_scale requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.dateset_shift_scale(arg0, arg1, arg2, arg3, arg4);
    }

    /**
     * MEOS {@code dateset_start_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int dateset_start_value(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "dateset_start_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.dateset_start_value(arg0);
    }

    /**
     * MEOS {@code dateset_value_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer dateset_value_n(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "dateset_value_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.dateset_value_n(arg0, arg1);
    }

    /**
     * MEOS {@code dateset_values} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer dateset_values(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "dateset_values requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.dateset_values(arg0, arg1);
    }

    /**
     * MEOS {@code dateset_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer dateset_in(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "dateset_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.dateset_in(arg0);
    }

    /**
     * MEOS {@code dateset_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String dateset_out(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "dateset_out requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.dateset_out(arg0);
    }

}
