#!/usr/bin/env python3
"""Free-fns expansion: emit Flink-side static facades for the streamable
MEOS public functions that are NOT assigned to an OO class in the
object model. Organized per source header (one Java class per header)
to keep navigability close to MEOS' own source layout.

Reads:
- JMEOS PR #19's functions.GeneratedFunctions surface (2,699 methods)
- streaming-relevance baseline v4 (2,240 public-API fns, classified)

Emits:
- MeosOpsFree<HeaderName>.java — one per public header
- Shares MeosOpsRuntime (single MEOS_AVAILABLE flag across all facades)
"""
import json, re, sys, datetime
from pathlib import Path
from collections import Counter, defaultdict

SIG_PATH = Path("/home/esteban/src/_flink_codegen/jmeos_pr19_signatures.txt")
BL_PATH  = Path("/home/esteban/src/_streaming_relevance/out/streaming-relevance-baseline.json")
OUT_ROOT = Path("/home/esteban/src/_flink_codegen/generated")
OUT_PKG  = "org.mobilitydb.flink.meos"
OUT_DIR  = OUT_ROOT / "src/main/java" / OUT_PKG.replace('.', '/')

SIG_RE = re.compile(r'^\s*public\s+static\s+(?P<ret>[\w\.<>\[\]]+)\s+(?P<name>\w+)\((?P<args>[^)]*)\)')
jmeos = {}
with open(SIG_PATH) as f:
    for line in f:
        m = SIG_RE.match(line.rstrip(';\n'))
        if m:
            jmeos[m.group('name')] = {
                'ret': m.group('ret'),
                'arg_types': [a.strip() for a in m.group('args').strip().split(',')] if m.group('args').strip() else []
            }
print(f'JMEOS methods parsed: {len(jmeos)}')

with open(BL_PATH) as f: bl = json.load(f)

# Emit-tier set (same as v4)
EMIT_TIERS = {'stateless', 'bounded-state', 'windowed', 'cross-stream', 'io-meta'}

# Free fns = streamable + NOT classified into any OO class + public header
free_rows = [r for r in bl['functions']
             if r['tier'] in EMIT_TIERS
             and not r.get('class')        # no OO class
             and r['tier'] != 'internal']

print(f'free-fn target (baseline streamable + no OO class): {len(free_rows)}')

# Inner-join with JMEOS PR #19
emit_rows = []
not_in_jmeos = []
for r in free_rows:
    if r['name'] in jmeos:
        sig = jmeos[r['name']]
        emit_rows.append({**r,
                          'java_ret': sig['ret'],
                          'java_params': [(t, f'arg{i}') for i, t in enumerate(sig['arg_types'])]})
    else:
        not_in_jmeos.append(r['name'])

print(f'JMEOS inner-join: {len(emit_rows)} emit / {len(not_in_jmeos)} absent')

# Group by header — produce one Java class per header
by_header = defaultdict(list)
for r in emit_rows:
    by_header[r['file']].append(r)

# Header → Java class name
def header_to_class(h):
    # meos.h → MeosOpsFreeCore
    # meos_geo.h → MeosOpsFreeGeo
    # meos_cbuffer.h → MeosOpsFreeCbuffer
    base = h.replace('.h', '').replace('meos_', '').replace('meos', 'core')
    if base in ('', 'core'):
        return 'MeosOpsFreeCore'
    parts = base.split('_')
    return 'MeosOpsFree' + ''.join(p.capitalize() for p in parts)

TIER_DOC = {
    'stateless':     'Pure per-event; safe in any Flink scalar position.',
    'bounded-state': 'Per-event with bounded per-key state (MEOS handle).',
    'windowed':      'Requires window operator — caller wraps in AggregateFunction.',
    'cross-stream':  'Pairwise across streams — caller wraps in a join.',
    'sequence-only': 'Inherently non-streamable; honest marker.',
    'io-meta':       'I/O / catalog / lifecycle helper.',
}

def short_type(t):
    if t.startswith('java.lang.'):
        return t[len('java.lang.'):]
    return t.split('.')[-1] if '.' in t else t

def emit(cls_name, rows, header):
    imports = set(['functions.GeneratedFunctions'])
    for r in rows:
        for t in [r['java_ret']] + [a[0] for a in r['java_params']]:
            if '.' in t and not t.startswith('java.lang.'):
                imports.add(t.replace('[]', ''))
    imports = sorted(i for i in imports if '.' in i)

    tier_cnt = Counter(r['tier'] for r in rows)
    L = [
        f'package {OUT_PKG};',
        '',
        f'/* AUTO-GENERATED by codegen_flink_free.py — do not edit by hand.',
        f' * Source header: {header}',
        f' * Methods emitted: {len(rows)} (' + ' · '.join(f'{t}={c}' for t, c in tier_cnt.most_common()) + ')',
        f' * Scope: MEOS public functions NOT classified into any object-model class',
        f' *        (free functions, not methods on a class).',
        f' * Source: JMEOS PR #19 (functions.GeneratedFunctions) ∩ streaming-relevance baseline v4.',
        ' */',
        '',
    ]
    for i in imports:
        L.append(f'import {i};')
    L += [
        '',
        f'public final class {cls_name} {{',
        '',
        '    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;',
        '',
        f'    private {cls_name}() {{ /* utility */ }}',
        '',
    ]

    TIER_ORDER = {'stateless':0, 'bounded-state':1, 'windowed':2, 'cross-stream':3, 'io-meta':4, 'sequence-only':5}
    for r in sorted(rows, key=lambda r: (TIER_ORDER.get(r['tier'], 99), r['name'])):
        fname = r['name']
        args = ', '.join(f'{short_type(t)} {n}' for (t, n) in r['java_params'])
        call_args = ', '.join(n for (t, n) in r['java_params'])
        ret_short = short_type(r['java_ret'])
        L += [
            '    /**',
            f'     * MEOS {{@code {fname}}} — tier <b>{r["tier"]}</b>.',
            f'     * <p>{TIER_DOC.get(r["tier"], "")}</p>',
            f'     * <p>Free function (not class-classified). Classification rule: {r["reason"]}</p>',
            '     */',
        ]
        if r['tier'] == 'sequence-only':
            L += [
                f'    public static {ret_short} {fname}({args}) {{',
                f'        throw new UnsupportedOperationException(',
                f'            "{fname} is sequence-only — not supported in a streaming context");',
                '    }', '',
            ]
        else:
            ret_stmt = '' if ret_short == 'void' else 'return '
            L += [
                f'    public static {ret_short} {fname}({args}) {{',
                '        if (!MEOS_AVAILABLE) {',
                f'            throw new UnsupportedOperationException(',
                f'                "{fname} requires libmeos — set -Dmobilityflink.meos.enabled=true");',
                '        }',
                f'        {ret_stmt}GeneratedFunctions.{fname}({call_args});',
                '    }', '',
            ]
    L.append('}')
    return '\n'.join(L) + '\n'

emitted_files = []
for header, rows in sorted(by_header.items()):
    cls = header_to_class(header)
    (OUT_DIR / f'{cls}.java').write_text(emit(cls, rows, header))
    emitted_files.append((cls, header, len(rows)))

print(f'\n=== emitted {len(emitted_files)} free-fn Java classes ===')
for cls, hdr, n in sorted(emitted_files, key=lambda x: -x[2]):
    print(f'  {cls:30s}  ({hdr:25s}): {n} methods')

# Manifest
manifest = {
    'generator': 'codegen_flink_free.py',
    'jmeos_method_total': len(jmeos),
    'baseline_free_fn_count': len(free_rows),
    'emitted_methods': len(emit_rows),
    'absent_from_jmeos': len(not_in_jmeos),
    'absent_from_jmeos_sample': not_in_jmeos[:20],
    'tier_breakdown': dict(Counter(r['tier'] for r in emit_rows)),
    'classes_emitted': sorted([cls for cls, _, _ in emitted_files]),
    'methods_per_header': {hdr: n for cls, hdr, n in emitted_files},
}
(OUT_ROOT / 'meos-ops-free-manifest.json').write_text(json.dumps(manifest, indent=2))
print(f'\nwrote meos-ops-free-manifest.json')
print(f'\ntier breakdown of emitted free fns:')
for t, c in Counter(r['tier'] for r in emit_rows).most_common():
    print(f'  {t:18s}: {c}')
