package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TGeometry
 * Methods emitted: 5 (stateless=3 · io-meta=2)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTGeometry {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTGeometry() { /* utility */ }

    /**
     * MEOS {@code tgeometry_to_tcbuffer} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tgeometry_to_tcbuffer(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeometry_to_tcbuffer requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeometry_to_tcbuffer(arg0);
    }

    /**
     * MEOS {@code tgeometry_to_tgeography} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tgeometry_to_tgeography(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeometry_to_tgeography requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeometry_to_tgeography(arg0);
    }

    /**
     * MEOS {@code tgeometry_to_tgeompoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tgeometry_to_tgeompoint(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeometry_to_tgeompoint requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeometry_to_tgeompoint(arg0);
    }

    /**
     * MEOS {@code tgeometry_from_mfjson} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tgeometry_from_mfjson(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeometry_from_mfjson requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeometry_from_mfjson(arg0);
    }

    /**
     * MEOS {@code tgeometry_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tgeometry_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeometry_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeometry_in(arg0);
    }

}
