package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TPoint
 * Methods emitted: 24 (bounded-state=20 · stateless=2 · windowed=2)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTPoint {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTPoint() { /* utility */ }

    /**
     * MEOS {@code tpoint_from_base_temp} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static Pointer tpoint_from_base_temp(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_from_base_temp requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_from_base_temp(arg0, arg1);
    }

    /**
     * MEOS {@code tpoint_tfloat_to_geomeas} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static int tpoint_tfloat_to_geomeas(Pointer arg0, Pointer arg1, int arg2, Pointer arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_tfloat_to_geomeas requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_tfloat_to_geomeas(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code tpoint_angular_difference} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpoint_angular_difference(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_angular_difference requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_angular_difference(arg0);
    }

    /**
     * MEOS {@code tpoint_as_mvtgeom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int tpoint_as_mvtgeom(Pointer arg0, Pointer arg1, int arg2, int arg3, int arg4, Pointer arg5, Pointer arg6, Pointer arg7) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_as_mvtgeom requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_as_mvtgeom(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    /**
     * MEOS {@code tpoint_at_elevation} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tpoint_at_elevation(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_at_elevation requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_at_elevation(arg0, arg1);
    }

    /**
     * MEOS {@code tpoint_at_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tpoint_at_geom(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_at_geom requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_at_geom(arg0, arg1);
    }

    /**
     * MEOS {@code tpoint_at_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tpoint_at_value(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_at_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_at_value(arg0, arg1);
    }

    /**
     * MEOS {@code tpoint_azimuth} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpoint_azimuth(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_azimuth requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_azimuth(arg0);
    }

    /**
     * MEOS {@code tpoint_cumulative_length} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpoint_cumulative_length(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_cumulative_length requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_cumulative_length(arg0);
    }

    /**
     * MEOS {@code tpoint_direction} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int tpoint_direction(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_direction requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_direction(arg0, arg1);
    }

    /**
     * MEOS {@code tpoint_get_x} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpoint_get_x(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_get_x requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_get_x(arg0);
    }

    /**
     * MEOS {@code tpoint_get_y} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpoint_get_y(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_get_y requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_get_y(arg0);
    }

    /**
     * MEOS {@code tpoint_get_z} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpoint_get_z(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_get_z requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_get_z(arg0);
    }

    /**
     * MEOS {@code tpoint_is_simple} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int tpoint_is_simple(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_is_simple requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_is_simple(arg0);
    }

    /**
     * MEOS {@code tpoint_length} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double tpoint_length(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_length requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_length(arg0);
    }

    /**
     * MEOS {@code tpoint_make_simple} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpoint_make_simple(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_make_simple requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_make_simple(arg0, arg1);
    }

    /**
     * MEOS {@code tpoint_minus_elevation} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tpoint_minus_elevation(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_minus_elevation requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_minus_elevation(arg0, arg1);
    }

    /**
     * MEOS {@code tpoint_minus_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tpoint_minus_geom(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_minus_geom requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_minus_geom(arg0, arg1);
    }

    /**
     * MEOS {@code tpoint_minus_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tpoint_minus_value(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_minus_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_minus_value(arg0, arg1);
    }

    /**
     * MEOS {@code tpoint_speed} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpoint_speed(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_speed requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_speed(arg0);
    }

    /**
     * MEOS {@code tpoint_trajectory} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpoint_trajectory(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_trajectory requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_trajectory(arg0, arg1);
    }

    /**
     * MEOS {@code tpoint_twcentroid} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpoint_twcentroid(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_twcentroid requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_twcentroid(arg0);
    }

    /**
     * MEOS {@code tpoint_tcentroid_finalfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer tpoint_tcentroid_finalfn(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_tcentroid_finalfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_tcentroid_finalfn(arg0);
    }

    /**
     * MEOS {@code tpoint_tcentroid_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer tpoint_tcentroid_transfn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpoint_tcentroid_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpoint_tcentroid_transfn(arg0, arg1);
    }

}
