package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TstzSet
 * Methods emitted: 12 (bounded-state=6 · stateless=3 · io-meta=2 · windowed=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTstzSet {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTstzSet() { /* utility */ }

    /**
     * MEOS {@code tstzset_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static jnr.ffi.Pointer tstzset_make(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tstzset_make requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tstzset_make(arg0, arg1);
    }

    /**
     * MEOS {@code tstzset_to_dateset} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tstzset_to_dateset(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tstzset_to_dateset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tstzset_to_dateset(arg0);
    }

    /**
     * MEOS {@code tstzset_to_stbox} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tstzset_to_stbox(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tstzset_to_stbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tstzset_to_stbox(arg0);
    }

    /**
     * MEOS {@code tstzset_end_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static java.time.OffsetDateTime tstzset_end_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tstzset_end_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tstzset_end_value(arg0);
    }

    /**
     * MEOS {@code tstzset_shift_scale} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tstzset_shift_scale(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, jnr.ffi.Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tstzset_shift_scale requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tstzset_shift_scale(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tstzset_start_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static java.time.OffsetDateTime tstzset_start_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tstzset_start_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tstzset_start_value(arg0);
    }

    /**
     * MEOS {@code tstzset_tprecision} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tstzset_tprecision(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, java.time.OffsetDateTime arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tstzset_tprecision requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tstzset_tprecision(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tstzset_value_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tstzset_value_n(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tstzset_value_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tstzset_value_n(arg0, arg1);
    }

    /**
     * MEOS {@code tstzset_values} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tstzset_values(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tstzset_values requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tstzset_values(arg0);
    }

    /**
     * MEOS {@code tstzset_tcount_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static jnr.ffi.Pointer tstzset_tcount_transfn(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tstzset_tcount_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tstzset_tcount_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code tstzset_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tstzset_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tstzset_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tstzset_in(arg0);
    }

    /**
     * MEOS {@code tstzset_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static java.lang.String tstzset_out(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tstzset_out requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tstzset_out(arg0);
    }

}
