package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: FloatSpan
 * Methods emitted: 15 (bounded-state=11 · io-meta=2 · stateless=2)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsFloatSpan {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsFloatSpan() { /* utility */ }

    /**
     * MEOS {@code floatspan_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static jnr.ffi.Pointer floatspan_make(double arg0, double arg1, boolean arg2, boolean arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_make requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_make(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code floatspan_to_intspan} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer floatspan_to_intspan(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_to_intspan requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_to_intspan(arg0);
    }

    /**
     * MEOS {@code floatspan_bins} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspan_bins(jnr.ffi.Pointer arg0, double arg1, double arg2, jnr.ffi.Pointer arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_bins requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_bins(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code floatspan_ceil} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspan_ceil(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_ceil requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_ceil(arg0);
    }

    /**
     * MEOS {@code floatspan_degrees} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspan_degrees(jnr.ffi.Pointer arg0, boolean arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_degrees requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_degrees(arg0, arg1);
    }

    /**
     * MEOS {@code floatspan_expand} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspan_expand(jnr.ffi.Pointer arg0, double arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_expand requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_expand(arg0, arg1);
    }

    /**
     * MEOS {@code floatspan_floor} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspan_floor(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_floor requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_floor(arg0);
    }

    /**
     * MEOS {@code floatspan_lower} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double floatspan_lower(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_lower requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_lower(arg0);
    }

    /**
     * MEOS {@code floatspan_radians} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspan_radians(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_radians requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_radians(arg0);
    }

    /**
     * MEOS {@code floatspan_round} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspan_round(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_round requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_round(arg0, arg1);
    }

    /**
     * MEOS {@code floatspan_shift_scale} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer floatspan_shift_scale(jnr.ffi.Pointer arg0, double arg1, double arg2, boolean arg3, boolean arg4) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_shift_scale requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_shift_scale(arg0, arg1, arg2, arg3, arg4);
    }

    /**
     * MEOS {@code floatspan_upper} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double floatspan_upper(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_upper requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_upper(arg0);
    }

    /**
     * MEOS {@code floatspan_width} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double floatspan_width(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_width requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_width(arg0);
    }

    /**
     * MEOS {@code floatspan_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer floatspan_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_in(arg0);
    }

    /**
     * MEOS {@code floatspan_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static java.lang.String floatspan_out(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "floatspan_out requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.floatspan_out(arg0, arg1);
    }

}
