package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TNpointInst
 * Methods emitted: 1 (stateless=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTNpointInst {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTNpointInst() { /* utility */ }

    /**
     * MEOS {@code tnpointinst_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static jnr.ffi.Pointer tnpointinst_make(jnr.ffi.Pointer arg0, java.time.OffsetDateTime arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpointinst_make requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpointinst_make(arg0, arg1);
    }

}
