package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TSequenceSet
 * Methods emitted: 1 (bounded-state=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTSequenceSet {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTSequenceSet() { /* utility */ }

    /**
     * MEOS {@code tsequenceset_make_gaps} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tsequenceset_make_gaps(Pointer arg0, int arg1, int arg2, Pointer arg3, double arg4) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tsequenceset_make_gaps requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tsequenceset_make_gaps(arg0, arg1, arg2, arg3, arg4);
    }

}
