package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TCbuffer
 * Methods emitted: 15 (bounded-state=10 · stateless=3 · io-meta=2)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTCbuffer {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTCbuffer() { /* utility */ }

    /**
     * MEOS {@code tcbuffer_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static Pointer tcbuffer_make(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_make requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_make(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_to_tfloat} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer tcbuffer_to_tfloat(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_to_tfloat requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_to_tfloat(arg0);
    }

    /**
     * MEOS {@code tcbuffer_to_tgeompoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer tcbuffer_to_tgeompoint(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_to_tgeompoint requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_to_tgeompoint(arg0);
    }

    /**
     * MEOS {@code tcbuffer_at_cbuffer} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tcbuffer_at_cbuffer(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_at_cbuffer requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_at_cbuffer(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_at_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tcbuffer_at_geom(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_at_geom requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_at_geom(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_at_stbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tcbuffer_at_stbox(Pointer arg0, Pointer arg1, int arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_at_stbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_at_stbox(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tcbuffer_expand} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tcbuffer_expand(Pointer arg0, double arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_expand requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_expand(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_minus_cbuffer} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tcbuffer_minus_cbuffer(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_minus_cbuffer requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_minus_cbuffer(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_minus_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tcbuffer_minus_geom(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_minus_geom requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_minus_geom(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_minus_stbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tcbuffer_minus_stbox(Pointer arg0, Pointer arg1, int arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_minus_stbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_minus_stbox(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tcbuffer_points} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tcbuffer_points(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_points requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_points(arg0);
    }

    /**
     * MEOS {@code tcbuffer_radius} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tcbuffer_radius(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_radius requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_radius(arg0);
    }

    /**
     * MEOS {@code tcbuffer_trav_area} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tcbuffer_trav_area(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_trav_area requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_trav_area(arg0, arg1);
    }

    /**
     * MEOS {@code tcbuffer_from_mfjson} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer tcbuffer_from_mfjson(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_from_mfjson requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_from_mfjson(arg0);
    }

    /**
     * MEOS {@code tcbuffer_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer tcbuffer_in(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tcbuffer_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tcbuffer_in(arg0);
    }

}
