package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TPose
 * Methods emitted: 17 (bounded-state=14 · stateless=2 · io-meta=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTPose {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTPose() { /* utility */ }

    /**
     * MEOS {@code tpose_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static Pointer tpose_make(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_make requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_make(arg0, arg1);
    }

    /**
     * MEOS {@code tpose_to_tpoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer tpose_to_tpoint(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_to_tpoint requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_to_tpoint(arg0);
    }

    /**
     * MEOS {@code tpose_at_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tpose_at_geom(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_at_geom requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_at_geom(arg0, arg1);
    }

    /**
     * MEOS {@code tpose_at_pose} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tpose_at_pose(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_at_pose requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_at_pose(arg0, arg1);
    }

    /**
     * MEOS {@code tpose_at_stbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tpose_at_stbox(Pointer arg0, Pointer arg1, int arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_at_stbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_at_stbox(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tpose_end_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpose_end_value(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_end_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_end_value(arg0);
    }

    /**
     * MEOS {@code tpose_minus_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tpose_minus_geom(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_minus_geom requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_minus_geom(arg0, arg1);
    }

    /**
     * MEOS {@code tpose_minus_pose} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tpose_minus_pose(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_minus_pose requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_minus_pose(arg0, arg1);
    }

    /**
     * MEOS {@code tpose_minus_stbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tpose_minus_stbox(Pointer arg0, Pointer arg1, int arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_minus_stbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_minus_stbox(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tpose_points} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpose_points(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_points requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_points(arg0);
    }

    /**
     * MEOS {@code tpose_rotation} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpose_rotation(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_rotation requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_rotation(arg0);
    }

    /**
     * MEOS {@code tpose_start_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpose_start_value(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_start_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_start_value(arg0);
    }

    /**
     * MEOS {@code tpose_trajectory} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpose_trajectory(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_trajectory requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_trajectory(arg0);
    }

    /**
     * MEOS {@code tpose_value_at_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static int tpose_value_at_timestamptz(Pointer arg0, int arg1, int arg2, Pointer arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_value_at_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_value_at_timestamptz(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code tpose_value_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int tpose_value_n(Pointer arg0, int arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_value_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_value_n(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tpose_values} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tpose_values(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_values requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_values(arg0, arg1);
    }

    /**
     * MEOS {@code tpose_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer tpose_in(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tpose_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tpose_in(arg0);
    }

}
