package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TGeomPoint
 * Methods emitted: 4 (io-meta=2 · stateless=2)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTGeomPoint {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTGeomPoint() { /* utility */ }

    /**
     * MEOS {@code tgeompoint_to_tgeometry} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tgeompoint_to_tgeometry(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeompoint_to_tgeometry requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeompoint_to_tgeometry(arg0);
    }

    /**
     * MEOS {@code tgeompoint_to_tnpoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tgeompoint_to_tnpoint(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeompoint_to_tnpoint requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeompoint_to_tnpoint(arg0);
    }

    /**
     * MEOS {@code tgeompoint_from_mfjson} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tgeompoint_from_mfjson(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeompoint_from_mfjson requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeompoint_from_mfjson(arg0);
    }

    /**
     * MEOS {@code tgeompoint_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tgeompoint_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeompoint_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeompoint_in(arg0);
    }

}
