package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: CbufferSet
 * Methods emitted: 7 (bounded-state=4 · io-meta=2 · stateless=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsCbufferSet {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsCbufferSet() { /* utility */ }

    /**
     * MEOS {@code cbufferset_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static jnr.ffi.Pointer cbufferset_make(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "cbufferset_make requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.cbufferset_make(arg0, arg1);
    }

    /**
     * MEOS {@code cbufferset_end_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer cbufferset_end_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "cbufferset_end_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.cbufferset_end_value(arg0);
    }

    /**
     * MEOS {@code cbufferset_start_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer cbufferset_start_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "cbufferset_start_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.cbufferset_start_value(arg0);
    }

    /**
     * MEOS {@code cbufferset_value_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer cbufferset_value_n(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "cbufferset_value_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.cbufferset_value_n(arg0, arg1);
    }

    /**
     * MEOS {@code cbufferset_values} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer cbufferset_values(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "cbufferset_values requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.cbufferset_values(arg0);
    }

    /**
     * MEOS {@code cbufferset_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer cbufferset_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "cbufferset_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.cbufferset_in(arg0);
    }

    /**
     * MEOS {@code cbufferset_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static java.lang.String cbufferset_out(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "cbufferset_out requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.cbufferset_out(arg0, arg1);
    }

}
