package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TNpoint
 * Methods emitted: 21 (bounded-state=16 · io-meta=3 · stateless=1 · windowed=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTNpoint {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTNpoint() { /* utility */ }

    /**
     * MEOS {@code tnpoint_to_tgeompoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer tnpoint_to_tgeompoint(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_to_tgeompoint requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_to_tgeompoint(arg0);
    }

    /**
     * MEOS {@code tnpoint_at_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tnpoint_at_geom(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_at_geom requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_at_geom(arg0, arg1);
    }

    /**
     * MEOS {@code tnpoint_at_npoint} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tnpoint_at_npoint(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_at_npoint requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_at_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code tnpoint_at_npointset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tnpoint_at_npointset(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_at_npointset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_at_npointset(arg0, arg1);
    }

    /**
     * MEOS {@code tnpoint_at_stbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tnpoint_at_stbox(Pointer arg0, Pointer arg1, int arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_at_stbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_at_stbox(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tnpoint_cumulative_length} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tnpoint_cumulative_length(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_cumulative_length requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_cumulative_length(arg0);
    }

    /**
     * MEOS {@code tnpoint_length} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static double tnpoint_length(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_length requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_length(arg0);
    }

    /**
     * MEOS {@code tnpoint_minus_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tnpoint_minus_geom(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_minus_geom requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_minus_geom(arg0, arg1);
    }

    /**
     * MEOS {@code tnpoint_minus_npoint} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tnpoint_minus_npoint(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_minus_npoint requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_minus_npoint(arg0, arg1);
    }

    /**
     * MEOS {@code tnpoint_minus_npointset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tnpoint_minus_npointset(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_minus_npointset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_minus_npointset(arg0, arg1);
    }

    /**
     * MEOS {@code tnpoint_minus_stbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tnpoint_minus_stbox(Pointer arg0, Pointer arg1, int arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_minus_stbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_minus_stbox(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tnpoint_positions} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tnpoint_positions(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_positions requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_positions(arg0, arg1);
    }

    /**
     * MEOS {@code tnpoint_route} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int tnpoint_route(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_route requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_route(arg0);
    }

    /**
     * MEOS {@code tnpoint_routes} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tnpoint_routes(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_routes requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_routes(arg0);
    }

    /**
     * MEOS {@code tnpoint_speed} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tnpoint_speed(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_speed requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_speed(arg0);
    }

    /**
     * MEOS {@code tnpoint_trajectory} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tnpoint_trajectory(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_trajectory requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_trajectory(arg0);
    }

    /**
     * MEOS {@code tnpoint_twcentroid} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tnpoint_twcentroid(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_twcentroid requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_twcentroid(arg0);
    }

    /**
     * MEOS {@code tnpoint_tcentroid_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer tnpoint_tcentroid_transfn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_tcentroid_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_tcentroid_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code tnpoint_from_mfjson} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer tnpoint_from_mfjson(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_from_mfjson requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_from_mfjson(arg0);
    }

    /**
     * MEOS {@code tnpoint_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer tnpoint_in(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_in(arg0);
    }

    /**
     * MEOS {@code tnpoint_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String tnpoint_out(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tnpoint_out requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tnpoint_out(arg0, arg1);
    }

}
