package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: GeogSet
 * Methods emitted: 1 (io-meta=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsGeogSet {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsGeogSet() { /* utility */ }

    /**
     * MEOS {@code geogset_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer geogset_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "geogset_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.geogset_in(arg0);
    }

}
