package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TGeography
 * Methods emitted: 4 (io-meta=2 · stateless=2)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTGeography {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTGeography() { /* utility */ }

    /**
     * MEOS {@code tgeography_to_tgeogpoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tgeography_to_tgeogpoint(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeography_to_tgeogpoint requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeography_to_tgeogpoint(arg0);
    }

    /**
     * MEOS {@code tgeography_to_tgeometry} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tgeography_to_tgeometry(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeography_to_tgeometry requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeography_to_tgeometry(arg0);
    }

    /**
     * MEOS {@code tgeography_from_mfjson} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tgeography_from_mfjson(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeography_from_mfjson requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeography_from_mfjson(arg0);
    }

    /**
     * MEOS {@code tgeography_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tgeography_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeography_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeography_in(arg0);
    }

}
