package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: SpanSet
 * Methods emitted: 30 (bounded-state=20 · io-meta=4 · stateless=3 · windowed=3)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsSpanSet {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsSpanSet() { /* utility */ }

    /**
     * MEOS {@code spanset_copy} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static Pointer spanset_copy(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_copy requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_copy(arg0);
    }

    /**
     * MEOS {@code spanset_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static Pointer spanset_make(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_make requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_make(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_to_tbox} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer spanset_to_tbox(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_to_tbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_to_tbox(arg0);
    }

    /**
     * MEOS {@code spanset_cmp} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int spanset_cmp(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_cmp requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_cmp(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_end_span} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer spanset_end_span(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_end_span requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_end_span(arg0);
    }

    /**
     * MEOS {@code spanset_eq} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int spanset_eq(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_eq requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_eq(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_ge} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int spanset_ge(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_ge requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_ge(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_gt} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int spanset_gt(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_gt requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_gt(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_hash} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int spanset_hash(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_hash requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_hash(arg0);
    }

    /**
     * MEOS {@code spanset_hash_extended} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int spanset_hash_extended(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_hash_extended requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_hash_extended(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_le} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int spanset_le(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_le requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_le(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_lower_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int spanset_lower_inc(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_lower_inc requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_lower_inc(arg0);
    }

    /**
     * MEOS {@code spanset_lt} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int spanset_lt(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_lt requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_lt(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_ne} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int spanset_ne(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_ne requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_ne(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_num_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int spanset_num_spans(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_num_spans requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_num_spans(arg0);
    }

    /**
     * MEOS {@code spanset_span} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer spanset_span(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_span requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_span(arg0);
    }

    /**
     * MEOS {@code spanset_span_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer spanset_span_n(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_span_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_span_n(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_spanarr} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer spanset_spanarr(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_spanarr requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_spanarr(arg0);
    }

    /**
     * MEOS {@code spanset_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer spanset_spans(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_spans requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_spans(arg0);
    }

    /**
     * MEOS {@code spanset_split_each_n_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer spanset_split_each_n_spans(Pointer arg0, int arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_split_each_n_spans requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_split_each_n_spans(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code spanset_split_n_spans} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer spanset_split_n_spans(Pointer arg0, int arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_split_n_spans requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_split_n_spans(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code spanset_start_span} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer spanset_start_span(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_start_span requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_start_span(arg0);
    }

    /**
     * MEOS {@code spanset_upper_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int spanset_upper_inc(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_upper_inc requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_upper_inc(arg0);
    }

    /**
     * MEOS {@code spanset_extent_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer spanset_extent_transfn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_extent_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_extent_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_union_finalfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer spanset_union_finalfn(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_union_finalfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_union_finalfn(arg0);
    }

    /**
     * MEOS {@code spanset_union_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer spanset_union_transfn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_union_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_union_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_as_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String spanset_as_hexwkb(Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_as_hexwkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_as_hexwkb(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_as_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer spanset_as_wkb(Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_as_wkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_as_wkb(arg0, arg1);
    }

    /**
     * MEOS {@code spanset_from_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer spanset_from_hexwkb(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_from_hexwkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_from_hexwkb(arg0);
    }

    /**
     * MEOS {@code spanset_from_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer spanset_from_wkb(Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "spanset_from_wkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.spanset_from_wkb(arg0, arg1);
    }

}
