package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TText
 * Methods emitted: 18 (bounded-state=12 · io-meta=3 · windowed=2 · stateless=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTText {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTText() { /* utility */ }

    /**
     * MEOS {@code ttext_from_base_temp} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static jnr.ffi.Pointer ttext_from_base_temp(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_from_base_temp requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_from_base_temp(arg0, arg1);
    }

    /**
     * MEOS {@code ttext_at_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer ttext_at_value(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_at_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_at_value(arg0, arg1);
    }

    /**
     * MEOS {@code ttext_end_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer ttext_end_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_end_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_end_value(arg0);
    }

    /**
     * MEOS {@code ttext_initcap} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer ttext_initcap(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_initcap requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_initcap(arg0);
    }

    /**
     * MEOS {@code ttext_lower} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer ttext_lower(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_lower requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_lower(arg0);
    }

    /**
     * MEOS {@code ttext_max_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer ttext_max_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_max_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_max_value(arg0);
    }

    /**
     * MEOS {@code ttext_min_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer ttext_min_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_min_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_min_value(arg0);
    }

    /**
     * MEOS {@code ttext_minus_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static jnr.ffi.Pointer ttext_minus_value(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_minus_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_minus_value(arg0, arg1);
    }

    /**
     * MEOS {@code ttext_start_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer ttext_start_value(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_start_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_start_value(arg0);
    }

    /**
     * MEOS {@code ttext_upper} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer ttext_upper(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_upper requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_upper(arg0);
    }

    /**
     * MEOS {@code ttext_value_at_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static boolean ttext_value_at_timestamptz(jnr.ffi.Pointer arg0, java.time.OffsetDateTime arg1, boolean arg2, jnr.ffi.Pointer arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_value_at_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_value_at_timestamptz(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code ttext_value_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer ttext_value_n(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_value_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_value_n(arg0, arg1);
    }

    /**
     * MEOS {@code ttext_values} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer ttext_values(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_values requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_values(arg0, arg1);
    }

    /**
     * MEOS {@code ttext_tmax_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static jnr.ffi.Pointer ttext_tmax_transfn(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_tmax_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_tmax_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code ttext_tmin_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static jnr.ffi.Pointer ttext_tmin_transfn(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_tmin_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_tmin_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code ttext_from_mfjson} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer ttext_from_mfjson(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_from_mfjson requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_from_mfjson(arg0);
    }

    /**
     * MEOS {@code ttext_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer ttext_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_in(arg0);
    }

    /**
     * MEOS {@code ttext_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static java.lang.String ttext_out(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "ttext_out requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.ttext_out(arg0);
    }

}
