package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TBox
 * Methods emitted: 33 (bounded-state=22 · io-meta=6 · stateless=5)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTBox {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTBox() { /* utility */ }

    /**
     * MEOS {@code tbox_copy} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static jnr.ffi.Pointer tbox_copy(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_copy requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_copy(arg0);
    }

    /**
     * MEOS {@code tbox_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static jnr.ffi.Pointer tbox_make(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_make requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_make(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_to_floatspan} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tbox_to_floatspan(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_to_floatspan requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_to_floatspan(arg0);
    }

    /**
     * MEOS {@code tbox_to_intspan} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tbox_to_intspan(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_to_intspan requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_to_intspan(arg0);
    }

    /**
     * MEOS {@code tbox_to_tstzspan} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static jnr.ffi.Pointer tbox_to_tstzspan(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_to_tstzspan requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_to_tstzspan(arg0);
    }

    /**
     * MEOS {@code tbox_cmp} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int tbox_cmp(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_cmp requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_cmp(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_eq} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean tbox_eq(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_eq requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_eq(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_expand_time} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tbox_expand_time(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_expand_time requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_expand_time(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_ge} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean tbox_ge(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_ge requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_ge(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_gt} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean tbox_gt(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_gt requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_gt(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_hash} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int tbox_hash(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_hash requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_hash(arg0);
    }

    /**
     * MEOS {@code tbox_hash_extended} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static long tbox_hash_extended(jnr.ffi.Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_hash_extended requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_hash_extended(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_hast} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean tbox_hast(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_hast requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_hast(arg0);
    }

    /**
     * MEOS {@code tbox_hasx} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean tbox_hasx(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_hasx requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_hasx(arg0);
    }

    /**
     * MEOS {@code tbox_le} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean tbox_le(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_le requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_le(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_lt} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean tbox_lt(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_lt requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_lt(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_ne} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static boolean tbox_ne(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_ne requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_ne(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_round} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tbox_round(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_round requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_round(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_shift_scale_time} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tbox_shift_scale_time(jnr.ffi.Pointer arg0, jnr.ffi.Pointer arg1, jnr.ffi.Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_shift_scale_time requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_shift_scale_time(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tbox_tmax} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tbox_tmax(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_tmax requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_tmax(arg0);
    }

    /**
     * MEOS {@code tbox_tmax_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tbox_tmax_inc(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_tmax_inc requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_tmax_inc(arg0);
    }

    /**
     * MEOS {@code tbox_tmin} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tbox_tmin(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_tmin requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_tmin(arg0);
    }

    /**
     * MEOS {@code tbox_tmin_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tbox_tmin_inc(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_tmin_inc requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_tmin_inc(arg0);
    }

    /**
     * MEOS {@code tbox_xmax} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tbox_xmax(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_xmax requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_xmax(arg0);
    }

    /**
     * MEOS {@code tbox_xmax_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tbox_xmax_inc(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_xmax_inc requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_xmax_inc(arg0);
    }

    /**
     * MEOS {@code tbox_xmin} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tbox_xmin(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_xmin requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_xmin(arg0);
    }

    /**
     * MEOS {@code tbox_xmin_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static jnr.ffi.Pointer tbox_xmin_inc(jnr.ffi.Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_xmin_inc requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_xmin_inc(arg0);
    }

    /**
     * MEOS {@code tbox_as_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static java.lang.String tbox_as_hexwkb(jnr.ffi.Pointer arg0, byte arg1, jnr.ffi.Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_as_hexwkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_as_hexwkb(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tbox_as_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tbox_as_wkb(jnr.ffi.Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_as_wkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_as_wkb(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_from_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tbox_from_hexwkb(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_from_hexwkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_from_hexwkb(arg0);
    }

    /**
     * MEOS {@code tbox_from_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tbox_from_wkb(jnr.ffi.Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_from_wkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_from_wkb(arg0, arg1);
    }

    /**
     * MEOS {@code tbox_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static jnr.ffi.Pointer tbox_in(java.lang.String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_in(arg0);
    }

    /**
     * MEOS {@code tbox_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static java.lang.String tbox_out(jnr.ffi.Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tbox_out requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tbox_out(arg0, arg1);
    }

}
