package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TSpatial
 * Methods emitted: 9 (bounded-state=4 · io-meta=3 · stateless=1 · windowed=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTSpatial {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTSpatial() { /* utility */ }

    /**
     * MEOS {@code tspatial_to_stbox} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer tspatial_to_stbox(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tspatial_to_stbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tspatial_to_stbox(arg0);
    }

    /**
     * MEOS {@code tspatial_set_srid} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tspatial_set_srid(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tspatial_set_srid requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tspatial_set_srid(arg0, arg1);
    }

    /**
     * MEOS {@code tspatial_srid} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int tspatial_srid(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tspatial_srid requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tspatial_srid(arg0);
    }

    /**
     * MEOS {@code tspatial_transform} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tspatial_transform(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tspatial_transform requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tspatial_transform(arg0, arg1);
    }

    /**
     * MEOS {@code tspatial_transform_pipeline} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tspatial_transform_pipeline(Pointer arg0, String arg1, int arg2, int arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tspatial_transform_pipeline requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tspatial_transform_pipeline(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code tspatial_extent_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer tspatial_extent_transfn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tspatial_extent_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tspatial_extent_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code tspatial_as_ewkt} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String tspatial_as_ewkt(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tspatial_as_ewkt requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tspatial_as_ewkt(arg0, arg1);
    }

    /**
     * MEOS {@code tspatial_as_text} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String tspatial_as_text(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tspatial_as_text requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tspatial_as_text(arg0, arg1);
    }

    /**
     * MEOS {@code tspatial_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String tspatial_out(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tspatial_out requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tspatial_out(arg0, arg1);
    }

}
