package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: Span
 * Methods emitted: 20 (bounded-state=11 · io-meta=4 · stateless=3 · windowed=2)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsSpan {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsSpan() { /* utility */ }

    /**
     * MEOS {@code span_copy} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static Pointer span_copy(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_copy requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_copy(arg0);
    }

    /**
     * MEOS {@code span_to_spanset} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer span_to_spanset(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_to_spanset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_to_spanset(arg0);
    }

    /**
     * MEOS {@code span_to_tbox} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer span_to_tbox(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_to_tbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_to_tbox(arg0);
    }

    /**
     * MEOS {@code span_cmp} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int span_cmp(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_cmp requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_cmp(arg0, arg1);
    }

    /**
     * MEOS {@code span_eq} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int span_eq(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_eq requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_eq(arg0, arg1);
    }

    /**
     * MEOS {@code span_ge} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int span_ge(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_ge requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_ge(arg0, arg1);
    }

    /**
     * MEOS {@code span_gt} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int span_gt(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_gt requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_gt(arg0, arg1);
    }

    /**
     * MEOS {@code span_hash} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int span_hash(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_hash requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_hash(arg0);
    }

    /**
     * MEOS {@code span_hash_extended} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int span_hash_extended(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_hash_extended requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_hash_extended(arg0, arg1);
    }

    /**
     * MEOS {@code span_le} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int span_le(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_le requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_le(arg0, arg1);
    }

    /**
     * MEOS {@code span_lower_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int span_lower_inc(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_lower_inc requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_lower_inc(arg0);
    }

    /**
     * MEOS {@code span_lt} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int span_lt(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_lt requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_lt(arg0, arg1);
    }

    /**
     * MEOS {@code span_ne} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code predicate}.</p>
     * <p>Classification: predicate on 1 temporal</p>
     */
    public static int span_ne(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_ne requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_ne(arg0, arg1);
    }

    /**
     * MEOS {@code span_upper_inc} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int span_upper_inc(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_upper_inc requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_upper_inc(arg0);
    }

    /**
     * MEOS {@code span_extent_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer span_extent_transfn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_extent_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_extent_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code span_union_transfn} — tier <b>windowed</b>.
     * <p>Requires window operator — caller wraps in AggregateFunction.</p>
     * <p>Object-model role: {@code aggregate}.</p>
     * <p>Classification: role=aggregate</p>
     */
    public static Pointer span_union_transfn(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_union_transfn requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_union_transfn(arg0, arg1);
    }

    /**
     * MEOS {@code span_as_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String span_as_hexwkb(Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_as_hexwkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_as_hexwkb(arg0, arg1);
    }

    /**
     * MEOS {@code span_as_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer span_as_wkb(Pointer arg0, byte arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_as_wkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_as_wkb(arg0, arg1);
    }

    /**
     * MEOS {@code span_from_hexwkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer span_from_hexwkb(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_from_hexwkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_from_hexwkb(arg0);
    }

    /**
     * MEOS {@code span_from_wkb} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer span_from_wkb(Pointer arg0, long arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "span_from_wkb requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.span_from_wkb(arg0, arg1);
    }

}
