package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TGeo
 * Methods emitted: 24 (bounded-state=23 · stateless=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsTGeo {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTGeo() { /* utility */ }

    /**
     * MEOS {@code tgeo_from_base_temp} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static Pointer tgeo_from_base_temp(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_from_base_temp requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_from_base_temp(arg0, arg1);
    }

    /**
     * MEOS {@code tgeo_affine} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_affine(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_affine requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_affine(arg0, arg1);
    }

    /**
     * MEOS {@code tgeo_at_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tgeo_at_geom(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_at_geom requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_at_geom(arg0, arg1);
    }

    /**
     * MEOS {@code tgeo_at_stbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tgeo_at_stbox(Pointer arg0, Pointer arg1, int arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_at_stbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_at_stbox(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tgeo_at_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tgeo_at_value(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_at_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_at_value(arg0, arg1);
    }

    /**
     * MEOS {@code tgeo_centroid} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_centroid(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_centroid requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_centroid(arg0);
    }

    /**
     * MEOS {@code tgeo_convex_hull} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_convex_hull(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_convex_hull requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_convex_hull(arg0);
    }

    /**
     * MEOS {@code tgeo_end_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_end_value(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_end_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_end_value(arg0);
    }

    /**
     * MEOS {@code tgeo_minus_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tgeo_minus_geom(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_minus_geom requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_minus_geom(arg0, arg1);
    }

    /**
     * MEOS {@code tgeo_minus_stbox} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tgeo_minus_stbox(Pointer arg0, Pointer arg1, int arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_minus_stbox requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_minus_stbox(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tgeo_minus_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static Pointer tgeo_minus_value(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_minus_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_minus_value(arg0, arg1);
    }

    /**
     * MEOS {@code tgeo_scale} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_scale(Pointer arg0, Pointer arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_scale requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_scale(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tgeo_space_boxes} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_space_boxes(Pointer arg0, double arg1, double arg2, double arg3, Pointer arg4, int arg5, int arg6, Pointer arg7) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_space_boxes requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_space_boxes(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    /**
     * MEOS {@code tgeo_space_split} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_space_split(Pointer arg0, double arg1, double arg2, double arg3, Pointer arg4, int arg5, int arg6, Pointer arg7, Pointer arg8) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_space_split requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_space_split(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    /**
     * MEOS {@code tgeo_space_time_boxes} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_space_time_boxes(Pointer arg0, double arg1, double arg2, double arg3, Pointer arg4, Pointer arg5, int arg6, int arg7, int arg8, Pointer arg9) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_space_time_boxes requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_space_time_boxes(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }

    /**
     * MEOS {@code tgeo_space_time_split} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_space_time_split(Pointer arg0, double arg1, double arg2, double arg3, Pointer arg4, Pointer arg5, int arg6, int arg7, int arg8, Pointer arg9, Pointer arg10, Pointer arg11) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_space_time_split requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_space_time_split(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
    }

    /**
     * MEOS {@code tgeo_split_each_n_stboxes} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_split_each_n_stboxes(Pointer arg0, int arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_split_each_n_stboxes requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_split_each_n_stboxes(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tgeo_split_n_stboxes} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_split_n_stboxes(Pointer arg0, int arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_split_n_stboxes requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_split_n_stboxes(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tgeo_start_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_start_value(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_start_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_start_value(arg0);
    }

    /**
     * MEOS {@code tgeo_stboxes} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_stboxes(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_stboxes requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_stboxes(arg0, arg1);
    }

    /**
     * MEOS {@code tgeo_traversed_area} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_traversed_area(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_traversed_area requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_traversed_area(arg0, arg1);
    }

    /**
     * MEOS {@code tgeo_value_at_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code restriction}.</p>
     * <p>Classification: role=restriction</p>
     */
    public static int tgeo_value_at_timestamptz(Pointer arg0, int arg1, int arg2, Pointer arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_value_at_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_value_at_timestamptz(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code tgeo_value_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int tgeo_value_n(Pointer arg0, int arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_value_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_value_n(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code tgeo_values} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer tgeo_values(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "tgeo_values requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.tgeo_values(arg0, arg1);
    }

}
