package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: BigintSpanSet
 * Methods emitted: 7 (bounded-state=5 · io-meta=2)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsBigintSpanSet {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsBigintSpanSet() { /* utility */ }

    /**
     * MEOS {@code bigintspanset_bins} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer bigintspanset_bins(Pointer arg0, int arg1, int arg2, Pointer arg3) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "bigintspanset_bins requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.bigintspanset_bins(arg0, arg1, arg2, arg3);
    }

    /**
     * MEOS {@code bigintspanset_lower} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int bigintspanset_lower(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "bigintspanset_lower requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.bigintspanset_lower(arg0);
    }

    /**
     * MEOS {@code bigintspanset_shift_scale} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer bigintspanset_shift_scale(Pointer arg0, int arg1, int arg2, int arg3, int arg4) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "bigintspanset_shift_scale requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.bigintspanset_shift_scale(arg0, arg1, arg2, arg3, arg4);
    }

    /**
     * MEOS {@code bigintspanset_upper} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int bigintspanset_upper(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "bigintspanset_upper requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.bigintspanset_upper(arg0);
    }

    /**
     * MEOS {@code bigintspanset_width} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int bigintspanset_width(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "bigintspanset_width requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.bigintspanset_width(arg0, arg1);
    }

    /**
     * MEOS {@code bigintspanset_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer bigintspanset_in(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "bigintspanset_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.bigintspanset_in(arg0);
    }

    /**
     * MEOS {@code bigintspanset_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String bigintspanset_out(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "bigintspanset_out requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.bigintspanset_out(arg0);
    }

}
