package org.mobilitydb.flink.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: PoseSet
 * Methods emitted: 7 (bounded-state=4 · io-meta=2 · stateless=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import jnr.ffi.Pointer;

public final class MeosOpsPoseSet {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsPoseSet() { /* utility */ }

    /**
     * MEOS {@code poseset_make} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: constructor of instant/scalar</p>
     */
    public static Pointer poseset_make(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "poseset_make requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.poseset_make(arg0, arg1);
    }

    /**
     * MEOS {@code poseset_end_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer poseset_end_value(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "poseset_end_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.poseset_end_value(arg0);
    }

    /**
     * MEOS {@code poseset_start_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer poseset_start_value(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "poseset_start_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.poseset_start_value(arg0);
    }

    /**
     * MEOS {@code poseset_value_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static int poseset_value_n(Pointer arg0, int arg1, Pointer arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "poseset_value_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.poseset_value_n(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code poseset_values} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer poseset_values(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "poseset_values requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.poseset_values(arg0);
    }

    /**
     * MEOS {@code poseset_in} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code constructor}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static Pointer poseset_in(String arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "poseset_in requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.poseset_in(arg0);
    }

    /**
     * MEOS {@code poseset_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String poseset_out(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "poseset_out requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.poseset_out(arg0, arg1);
    }

}
