#!/usr/bin/env python3
"""Generate the org.mobilitydb.meos.MeosOps* streaming facades from the MEOS
binding surface.

North Star (meos-api-codegen-regularity): the streaming facade surface is a
pure projection of the MEOS catalog and is GENERATED, never hand-written. The
facades are 1:1 static forwarders to functions.GeneratedFunctions (the JMEOS
FFI surface), so they always match the JMEOS jar bundled with this engine. The
streaming-relevance baseline classifies each MEOS function into an object-model
class and a streaming tier (stateless / bounded-state / windowed / cross-stream
/ io-meta); that drives one Java class per object-model class plus one per
source header for the free functions, with a shared MeosOpsRuntime that probes
libmeos exactly once per JVM.

This is the per-binding generator (the Flink/Kafka analogue of JMEOS'
FunctionsGenerator and MobilitySpark's tools/codegen_spark_udfs.py): each
engine runs it over the JMEOS jar it ships to regenerate its own facades, so
the surface never drifts from the pin and is reproducible from the repo.

Usage:
  tools/codegen_facades.py --jar <JMEOS.jar> --out <module-dir> --engine <name>
                           [--baseline <path>] [--package <pkg>]
"""
import argparse
import json
import os
import re
import subprocess
from collections import Counter, defaultdict
from pathlib import Path

SIG_RE = re.compile(
    r'^\s*public\s+static\s+(?P<ret>[\w\.<>\[\]]+)\s+(?P<name>\w+)\((?P<args>[^)]*)\)')

# Streaming tiers that get a facade; sequence-only/internal/ambiguous are skipped.
EMIT_TIERS = {'stateless', 'bounded-state', 'windowed', 'cross-stream', 'io-meta'}
TIER_ORDER = {'stateless': 0, 'bounded-state': 1, 'windowed': 2,
              'cross-stream': 3, 'io-meta': 4, 'sequence-only': 5}
TIER_DOC = {
    'stateless':     'Pure per-event; safe in any scalar position.',
    'bounded-state': 'Per-event with bounded per-key state (MEOS handle).',
    'windowed':      'Requires a window operator — caller wraps in an aggregate.',
    'cross-stream':  'Pairwise across streams — caller wraps in a join.',
    'sequence-only': 'Inherently non-streamable; honest marker.',
    'io-meta':       'I/O / catalog / lifecycle helper.',
}


def short_type(t):
    if t.startswith('java.lang.'):
        return t[len('java.lang.'):]
    return t.split('.')[-1] if '.' in t else t


def parse_jmeos_signatures(jar):
    """javap functions.GeneratedFunctions -> {name: {ret, arg_types}}."""
    out = subprocess.run(
        ['javap', '-cp', str(jar), 'functions.GeneratedFunctions'],
        check=True, capture_output=True, text=True).stdout
    jmeos = {}
    for line in out.splitlines():
        m = SIG_RE.match(line.rstrip(';'))
        if m:
            raw = m.group('args').strip()
            jmeos[m.group('name')] = {
                'ret': m.group('ret'),
                'arg_types': [a.strip() for a in raw.split(',')] if raw else [],
            }
    return jmeos


def header_to_class(h):
    base = h.replace('.h', '').replace('meos_', '').replace('meos', 'core')
    if base in ('', 'core'):
        return 'MeosOpsFreeCore'
    return 'MeosOpsFree' + ''.join(p.capitalize() for p in base.split('_'))


def collect_imports(rows):
    imports = {'functions.GeneratedFunctions'}
    for r in rows:
        for t in [r['java_ret']] + [a[0] for a in r['java_params']]:
            if '.' in t and not t.startswith('java.lang.'):
                imports.add(t.replace('[]', ''))
    return sorted(i for i in imports if '.' in i)


def emit_method(r, prop):
    fname = r['name']
    args = ', '.join(f'{short_type(t)} {n}' for (t, n) in r['java_params'])
    call_args = ', '.join(n for (t, n) in r['java_params'])
    ret = short_type(r['java_ret'])
    L = ['    /**',
         f'     * MEOS {{@code {fname}}} — tier <b>{r["tier"]}</b>.',
         f'     * <p>{TIER_DOC.get(r["tier"], "")}</p>']
    if r.get('role'):
        L.append(f'     * <p>Object-model role: {{@code {r["role"]}}}.</p>')
    L.append(f'     * <p>Classification: {r["reason"]}</p>')
    L.append('     */')
    if r['tier'] == 'sequence-only':
        L += [f'    public static {ret} {fname}({args}) {{',
              '        throw new UnsupportedOperationException(',
              f'            "{fname} is sequence-only — not supported in a streaming context");',
              '    }', '']
    else:
        ret_stmt = '' if ret == 'void' else 'return '
        L += [f'    public static {ret} {fname}({args}) {{',
              '        if (!MEOS_AVAILABLE) {',
              '            throw new UnsupportedOperationException(',
              f'                "{fname} requires libmeos — set -D{prop}=true");',
              '        }',
              f'        {ret_stmt}GeneratedFunctions.{fname}({call_args});',
              '    }', '']
    return L


def emit_class(cls, rows, pkg, prop, banner):
    tier_cnt = Counter(r['tier'] for r in rows)
    L = [f'package {pkg};', '',
         '/* AUTO-GENERATED by tools/codegen_facades.py — do not edit by hand.',
         f' * {banner}',
         f' * Methods emitted: {len(rows)} (' +
         ' · '.join(f'{t}={c}' for t, c in tier_cnt.most_common()) + ')',
         ' * Source: the bundled JMEOS functions.GeneratedFunctions surface',
         ' *         ∩ the streaming-relevance baseline.',
         ' */', '']
    L += [f'import {i};' for i in collect_imports(rows)]
    L += ['',
          f'public final class {cls} {{', '',
          '    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;',
          '',
          f'    private {cls}() {{ /* utility */ }}', '']
    for r in sorted(rows, key=lambda r: (TIER_ORDER.get(r['tier'], 99), r['name'])):
        L += emit_method(r, prop)
    L.append('}')
    return '\n'.join(L) + '\n'


def runtime_src(pkg, prop):
    return f'''package {pkg};

import functions.GeneratedFunctions;

/* AUTO-GENERATED by tools/codegen_facades.py — do not edit by hand.
 * Shared runtime helper: owns the single MEOS_AVAILABLE static-init across all
 * generated MeosOps* facades, so libmeos is probed exactly once per JVM. */
final class MeosOpsRuntime {{

    static final boolean MEOS_AVAILABLE;

    static {{
        boolean enabled = Boolean.parseBoolean(
                System.getProperty("{prop}", "true"));
        boolean ok = false;
        if (enabled) {{
            try {{
                GeneratedFunctions.meos_initialize();
                ok = true;
            }} catch (Throwable t) {{
                ok = false;
            }}
        }}
        MEOS_AVAILABLE = ok;
    }}

    private MeosOpsRuntime() {{ /* utility */ }}
}}
'''


def main():
    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--jar', required=True, help='JMEOS jar with functions.GeneratedFunctions')
    ap.add_argument('--out', required=True, help='module dir (facades go to <out>/src/main/java/<pkg>)')
    ap.add_argument('--engine', required=True, help='engine name -> the -Dmobility<engine>.meos.enabled toggle')
    ap.add_argument('--baseline', default=str(here / 'baseline' / 'streaming-relevance-baseline.json'))
    ap.add_argument('--package', default='org.mobilitydb.meos')
    a = ap.parse_args()

    prop = f'mobility{a.engine}.meos.enabled'
    out_dir = Path(a.out) / 'src/main/java' / a.package.replace('.', '/')
    out_dir.mkdir(parents=True, exist_ok=True)

    jmeos = parse_jmeos_signatures(a.jar)
    with open(a.baseline) as f:
        baseline = json.load(f)

    def join(rows):
        emit, absent = [], []
        for r in rows:
            if r['name'] in jmeos:
                sig = jmeos[r['name']]
                emit.append({**r, 'java_ret': sig['ret'],
                             'java_params': [(t, f'arg{i}') for i, t in enumerate(sig['arg_types'])]})
            else:
                absent.append(r['name'])
        return emit, absent

    streamable = [r for r in baseline['functions']
                  if r['tier'] in EMIT_TIERS and r['tier'] != 'internal']
    oo_rows, _ = join([r for r in streamable if r.get('class')])
    free_rows, _ = join([r for r in streamable if not r.get('class')])

    # Regenerate from scratch: drop stale MeosOps*.java, keep hand-written
    # caller logic in the same package (e.g. MeosSetSetJoin.java).
    for f in out_dir.glob('MeosOps*.java'):
        f.unlink()

    (out_dir / 'MeosOpsRuntime.java').write_text(runtime_src(a.package, prop))

    by_class = defaultdict(list)
    for r in oo_rows:
        for c in r['class']:
            by_class[c].append(r)
    for cls, rows in sorted(by_class.items()):
        (out_dir / f'MeosOps{cls}.java').write_text(
            emit_class(f'MeosOps{cls}', rows, a.package, prop,
                       f'MEOS object-model class: {cls}'))

    by_header = defaultdict(list)
    for r in free_rows:
        by_header[r['file']].append(r)
    for header, rows in sorted(by_header.items()):
        cls = header_to_class(header)
        (out_dir / f'{cls}.java').write_text(
            emit_class(cls, rows, a.package, prop, f'Free functions from {header}'))

    total = 1 + len(by_class) + len(by_header)
    print(f'{a.engine}: emitted {total} facade classes into {out_dir} '
          f'({len(by_class)} object-model + {len(by_header)} free + MeosOpsRuntime)')


if __name__ == '__main__':
    main()
